"""Remove url from quests

Revision ID: 910036d460d1
Revises: 30a5d27a9777
Create Date: 2024-12-10 15:35:51.070040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '910036d460d1'
down_revision: Union[str, None] = '30a5d27a9777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quests_url_key', 'quests', type_='unique')
    op.drop_column('quests', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('quests_url_key', 'quests', ['url'])
    # ### end Alembic commands ###
