"""Update Quest Model

Revision ID: ca8dc56d8f00
Revises: 4aeaa7b0cec9
Create Date: 2024-12-14 11:33:51.344142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca8dc56d8f00'
down_revision: Union[str, None] = '4aeaa7b0cec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('description', sa.TEXT(), nullable=True))
    op.drop_column('quests', 'full_description')
    op.drop_column('quests', 'brief_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('brief_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('quests', sa.Column('full_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('quests', 'description')
    # ### end Alembic commands ###
