"""Remove photo from questLine

Revision ID: e9224e9e783a
Revises: ca8dc56d8f00
Create Date: 2025-01-10 10:40:52.223138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9224e9e783a'
down_revision: Union[str, None] = 'ca8dc56d8f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quest_lines', 'photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quest_lines', sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
